server:
  port: 10909
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos
    routes:
      - name: 订单服务
        serviceName: dota-user-order
        location: /v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /
      - name: 用户服务
        serviceName: dota-user-service
        location: /user/v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /