server:
  port: 7771
#config service
spring:
  application:
    name: dota-user-order
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

basePath:
  /
