server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000 # 剔除服务时间间隔
    peer-node-connect-timeout-ms: 1000 # 链接超时
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: dota-eureka